### PR TITLE
Update trace by scroll-v4.2.7-temp version

### PR DESCRIPTION
**Pull request by mask-pp**
special traces change:
empty.json => bridge/01.json
greeter_setValue.json => greeter/setValue.json
native_transfer.json => native/transfer.json

### CODE REVIEW

**Comment by lispc** [comment]
Will bridge/01.json always be empty? (if traces got updated next time will bridge 01 still be empty？)

**Comment by mask-pp** [comment]
> 

Yeah, 01.json is always empty.

**Comment by 0xmountaintop** [comment]
bridge/01.json is always empty due to our clique consensus.

**Comment by lispc** [comment]
l1DataFee in bridge 01.json-19.json are all 0, is this ok?

**Comment by mask-pp** [comment]
> l1DataFee in bridge 01.json-19.json are all 0, is this ok?

It's ok, because set `setL1BaseFee` is is the last step.

**Pull request closed without merging**
