### PR TITLE
Update trace by scroll-v4.2.2

### PR DESCRIPTION
**Pull request by mask-pp**
Based on [trace-dumper](https://github.com/scroll-tech/trace-dumper/pull/24)

### CODE REVIEW

**Comment by 0xmountaintop** [comment]
we also need to think about a way to update `[bridge](https://github.com/scroll-tech/test-traces/tree/main/bridge)` traces.

you can borrow the idea from https://github.com/scroll-tech/testnet/blob/develop/scripts/fetch-traces.sh

**Comment by mask-pp** [comment]
> 

Appear an error when running `deploy-eips.sh`, others are running successfully.
error content: `(code: -32000, message: only replay-protected (EIP-155) transactions allowed over RPC, data: None)`

**Comment by lispc** [comment]
i will use the commit [7245cca](https://github.com/scroll-tech/test-traces/pull/12/commits/7245cca124ae82e8b07f5d7527548d73870d73ff) for a while. so don't force push or delete branch

**Comment by mask-pp** [comment]
> 

Fixed.

**Pull request merged**
